/** Verbatim from /how-solar-power-works/. */

export const powerFlow = [
  'Solar panels convert solar energy into electricity in DC form.',
  'DC current generated by the panels is converted into AC current by the DC-to-AC solar inverter.',
  'Generated power is measured by a solar meter before going to the electrical panel.',
  'AC current generated by solar power is then merged with the grid load at the main electrical panel.',
  'Any excess solar generation not used by the load goes to the grid (export)…',
  '…and supply is drawn from the grid (import) when solar power is not available.',
  'The utility grid (Torrent Power or DGVCL) supplies electricity and takes back the excess solar generation.',
]

export const flowConditions = [
  {
    title: 'Generation is less than the load',
    when: 'Daytime - condition 1',
    body: 'The additional power requirement is supplied by the grid. Some power is imported. No export.',
  },
  {
    title: 'Generation is more than the load',
    when: 'Daytime - condition 2',
    body: 'Excess solar generation is fed back to the grid. Power is exported. No import.',
  },
  {
    title: 'Solar power is not available',
    when: 'Night or evening',
    body: 'All power is imported from the utility grid - like a normal premises without a solar plant. No export, all import.',
  },
]

export const componentsIntro =
  'A grid-connected solar power system typically involves six basic components: solar panels, a DC-to-AC inverter, a solar generation meter, the main electrical (AC) distribution panel, a net meter, and the utility grid connection.'

export const netMetering =
  'Net metering measures the difference between the solar energy your system exports to the grid and the energy you import from it. Your DISCOM bills you on the net - so the units your roof sends back reduce what you pay.'
